version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 1111
       POSTGRES_DB: products
    networks:
      - product
  
  app:
    build: 
     context: .
     dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: products
    networks:
      - product

networks:
  product:
    driver: bridge